### PR TITLE
Small refactors

### PR DESCRIPTION
**Pull request by asterite**
Hi!

I just wanted to say that this library is awesome!! You are doing wonderful things :-)

Me and @waj wanted to have this for some time but we didn't really know well how to do it. We started thinking how to implements general mocks, but I think custom solutions like this are pretty good actually. I usually don't like mocks, but mocking Time is very useful and common because otherwise you have to use dependency injection and things like `IClock` or `TimeProvider` appear (I don't know if you ever had to program in Java or .Net), which are ugly. So for Time I like it. Another example for a useful mock is mocking `HTTP::Client`, and I guess something similar can be done (just replace the most low-level method, I think it's `exec`).

One thing I noted is that  `Time.new` isn't mocked. I think we can mock both `new` and `now` by using an undocumented feature (like many others): `previous_def`. You can see how it works by looking at [these specs](https://github.com/manastech/crystal/blob/master/spec/compiler/codegen/previous_def_spec.cr). But I now see a problem with using `previous_def` with `new`/`initialize`, so for now I think your way is more than good.

The changes in the commit are:
1. Use a more idiomatic way to say "use this, or that if nil"
2. Use `yield` instead of `blk.call`. When you do `blk.call` that creates a closure, which is a bit slower and captures local variables, and the type flow changes (kind of long to explain here, I'll document it sometime later in the official docs). But with `yield` the method always gets inlined. I think the same is true in Ruby.

### CODE REVIEW

**Comment by waterlink** [comment]
I see `previous_gen` might be very useful here

**Comment by waterlink** [comment]
LGTM

**Comment by waterlink** [comment]
Thanks @asterite!

**Comment by asterite** [comment]
Sorry to bother you again :-)

If I try this in a new project:

``` crystal
require "timecop"

Timecop.freeze(2.days.ago)
```

It gives an error: "there is no previous definition of 'new'". This is because there's no `Time.new` really, it's defined [with an initialize](https://github.com/manastech/crystal/blob/master/src/time/time.cr#L63).

So... how come it works in your specs? Well, if you invoke `Time.new` before requiring "timecop" then the compiler will generate a `new` method from the `initialize`, and so then there will be a previous def. And "spec" is [the one invoking Time.new](https://github.com/manastech/crystal/blob/master/src/spec/spec.cr#L147).

This means that timecop will work just fine in specs, but just by pure luck. I say this is a bug in Crystal, we need to think this better (but for now I don't know a solution). That's why in my first comment I said "But I now see a problem with using previous_def with new/initialize", but I didn't explain it at all (sorry).

I just tried this replacement and it works fine:

``` crystal
struct Time
  def initialize
    if Timecop.active?
      initialize Timecop.now.ticks
    else
      previous_def
    end
  end
end
```

This is a bit different because we must initialize the Time, and there's [another initialize](https://github.com/manastech/crystal/blob/master/src/time/time.cr#L67) that accepts the internal ticks, so we can use that.

Then I wondered what happens to the call to `Time.new` in "spec", before this redefinition. Well, today I found out (because when we implemented the "previous_def" feature we didn't realize it would work like that, but it does!) that that call will point to the original method, before the redefinition. You can see it with this program:

``` crystal
def foo
  p 1
end

puts "-"
foo

def foo
  p 2
  previous_def
end

puts "-"
foo

def foo
  p 3
  previous_def
end

puts "-"
foo
```

Anyway, sorry for the long text :-P But when you and others start writing programs in Crystal it's like a machinery that starts moving (and maybe in different ways then the ways we move it) and we can see how things really work and discover new things and patterns. Today I also tried to do a very basic mock for HTTP::Client and I can see that by redefining `HTTP::Client#exec` and using `previous_def` this will be very easy to do.

I'm also thinking, maybe it would be nice to be able to do `Spec.after_each { Timecop.reset }`, so you don't have to do that in every spec. What do you think? This seems to be tying the library to "spec", but if we standarize this and make any test framework provide a "Spec.after_each" method, then it won't be tied to a particular implementation.

**Comment by waterlink** [comment]
When I try this solution, it fixes the problem when there is no `.new` defined yet.

But specs fail. Because `.new` already defined (by run of `Time.now` from `spec`) and it doesn't get redefined.

**Comment by waterlink** [comment]
So one choice I see, is to actually call `Time.now` before re-defining, which sounds weird..

**Comment by asterite** [comment]
Aaah... right, that's the problem with `new`/`initialize` (I now understand it), `new` becomes this:

``` crystal
def self.new
  time = allocate
  time.initialize
  time
end
```

Then if you redefine `initialize` that `new` will still point to the old one.

I think for now you can leave your original solution, which works very well. Then if we find a better alternative we change it :-)

**Comment by asterite** [comment]
Or, instead of calling `Time.now` before re-defining you can do `typeof(Time.now)`, so the compiler types it (but no runtime code is generated), but it would still be a hack (relies on how the compiler works).

**Pull request merged**
